Nuclei JSON Input Support
projectdiscovery/openrisk pull request #25
Opened 2023-03-21 15:55 UTC by kchason

Addresses the last item in #6 to add support for parsing nuclei JSON reports
- Adds handling for `.jsonl` as an acceptable extension
- Parses the Nuclei JSON-Line results into a format consistent with the comma separated strings generated by `parseMD()`
- Updates the README(s) to add the supported type
- Fixes a typo in "unknown" for filtering results that don't impact the score

2023-03-28 11:25 UTC, tarunKoyalwar approved these changes
lgtm !

2023-03-28 17:02 UTC, dogancanbakir requested changes
@kchason Thanks for the PR!

Got an error while running against the following result.jsonl
```
{"template-id":"waf-detect","template-path":"/tmp/nuclei-templates/technologies/waf-detect.yaml","info":{"name":"WAF Detection","author":["dwisiswant0","lu4nx"],"tags":["waf","tech","misc"],"description":"A web application firewall was detected.","reference":["https://github.com/ekultek/whatwaf"],"severity":"info","classification":{"cve-id":[],"cwe-id":["cwe-200"]}},"matcher-name":"apachegeneric","type":"http","host":"http://target.com","matched-at":"http://target.com/","ip":"0.0.0.0","timestamp":"2023-03-09T16:28:12.32598+05:30","curl-command":"curl -X 'POST' -d '_=\u003cscript\u003ealert(1)\u003c/script\u003e' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Host: target.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36' 'http://target.com/'","matcher-status":true,"matched-line":null}
```

Error:
```
$ ./openrisk -i result.jsonl

                               _      __  
  ____  ____  ___  ____  _____(_)____/ /__
 / __ \/ __ \/ _ \/ __ \/ ___/ / ___/ //_/
/ /_/ / /_/ /  __/ / / / /  / (__  ) ,<   
\____/ .___/\___/_/ /_/_/  /_/____/_/|_|  Powered by OpenAI (GPT-3)
    /_/                                   v0.0.1 (experimental)                                          
  
                projectdiscovery.io

[ERR] failed to parse nuclei JSONL got json: cannot unmarshal array into Go struct field .Info.Classification.cve-id of type string
[RISK SCORE] Risk Score: 0 
Executive Summary: No vulnerabilities found.
```

This section causes the problem: 
```
"classification":{"cve-id":[]
```
Changing `[]` to `null` fixes the issue.

2023-03-29 00:28 UTC, kchason commented
> @kchason Thanks for the PR!
> 
> Got an error while running against the following result.jsonl
> 
> ```
> {"template-id":"waf-detect","template-path":"/tmp/nuclei-templates/technologies/waf-detect.yaml","info":{"name":"WAF Detection","author":["dwisiswant0","lu4nx"],"tags":["waf","tech","misc"],"description":"A web application firewall was detected.","reference":["https://github.com/ekultek/whatwaf"],"severity":"info","classification":{"cve-id":[],"cwe-id":["cwe-200"]}},"matcher-name":"apachegeneric","type":"http","host":"http://target.com","matched-at":"http://target.com/","ip":"0.0.0.0","timestamp":"2023-03-09T16:28:12.32598+05:30","curl-command":"curl -X 'POST' -d '_=\u003cscript\u003ealert(1)\u003c/script\u003e' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Host: target.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36' 'http://target.com/'","matcher-status":true,"matched-line":null}
> ```
> 
> Error:
> 
> ```
> $ ./openrisk -i result.jsonl
> 
>                                _      __  
>   ____  ____  ___  ____  _____(_)____/ /__
>  / __ \/ __ \/ _ \/ __ \/ ___/ / ___/ //_/
> / /_/ / /_/ /  __/ / / / /  / (__  ) ,<   
> \____/ .___/\___/_/ /_/_/  /_/____/_/|_|  Powered by OpenAI (GPT-3)
>     /_/                                   v0.0.1 (experimental)                                          
>   
>                 projectdiscovery.io
> 
> [ERR] failed to parse nuclei JSONL got json: cannot unmarshal array into Go struct field .Info.Classification.cve-id of type string
> [RISK SCORE] Risk Score: 0 
> Executive Summary: No vulnerabilities found.
> ```
> 
> This section causes the problem:
> 
> ```
> "classification":{"cve-id":[]
> ```
> 
> Changing `[]` to `null` fixes the issue.

Thanks for the feedback! I'll update this PR with a fix

2023-03-29 01:53 UTC, kchason commented
Updated the request to reduce the parsing surface. There were inconsistent types for `info.cve-id` being either a `string` or `[]string` type. Rather than unnecessarily complicate the logic to parse fields that aren't used, only the fields used in the issue template are unmarshaled.

This was tested against the error condition above (with `info.severity` set to `"medium"` so it's not excluded from the filter) and is working successfully as well as my prior test cases:
```json
{"template-id":"waf-detect","template-path":"/tmp/nuclei-templates/technologies/waf-detect.yaml","info":{"name":"WAF Detection","author":["dwisiswant0","lu4nx"],"tags":["waf","tech","misc"],"description":"A web application firewall was detected.","reference":["https://github.com/ekultek/whatwaf"],"severity":"medium","classification":{"cve-id":[],"cwe-id":["cwe-200"]}},"matcher-name":"apachegeneric","type":"http","host":"http://target.com","matched-at":"http://target.com/","ip":"0.0.0.0","timestamp":"2023-03-09T16:28:12.32598+05:30","curl-command":"curl -X 'POST' -d '_=\u003cscript\u003ealert(1)\u003c/script\u003e' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Host: target.com' -H 'User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36' 'http://target.com/'","matcher-status":true,"matched-line":null}
```

This commit also included default handling and excluding parsing fields that don't exist. This was tested against an empty object file (below):
```json
{}
```

2023-03-29 06:18 UTC, dogancanbakir approved these changes
LGTM

2023-03-29 07:07 UTC, ehsandeep approved these changes

2023-03-29 07:07 UTC, merged